jscraftcamp/website

- participants/marco_emrich.json
[X] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
[X] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
[X] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> add broken json file for Travis demonstration purposes

- participants/tristan_read.json
> add tristan read to participants

- src/_layout.ejs
@lujakob @cko @wolframkriesing : I realized that sharing our webpage link on facebook creates a rather ugly Link Photo (some pixeled letters like 'dece'). I'm trying to fix this here - but since I am no HTML Expert please check if I'm doing the right thing.
I took our Logo image from the Page instead.
> Added og-title and image for better facebook share behaviour

- test/participants.js
@cko @wolframkriesing : As we talked in #60 I added a test to disallow commas within tags to force our participants to put all tags as separate array elements.
> Added a test to check if any tag contains a comma  - and errors if so.

- participants/david_neubauer.json
> Add david_neubauer.json

- participants/stefan_richter.json
> registration for JS BarCamp (Stefan Richter)

- package.json
#JSCC16 is over - but we should already think about #JSCC17. I had trouble with `npm install`ing the website with the harp version specified - so I updated it to 0.21.0.
> Increased harp version to avoid failing build on linux systems

- src/index.ejs
This improves the sponsor section layout on the start page, especially on mobile devices.
On mobile: 
On mobile:
On desktop:
> fix(Start): improve sponsor layout

- src/js/index.js
the sponsoring page doesn't have a google map, so initialization failed. This checks for the google object to be available first.
> get rid of google error message

- participants/jonathan_haeberle.json
> Add Jonathan Häberle to participants

- participants/marco_emrich.json
> add marco emrich to participants

- participants/stesie.json
> add stefan siegl to list of participants

- participants/simon_kindlein.json
- [ x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute` 
(Btw.: 'what_can_i_contribute' is not marked as madantory on your registration page's docu - you might want to change it ;))
> added register json

- participants/sergii_paryzhskyi.json
> Add Sergii Paryzhskyi to participants

- package.json
There is no need to pass `-p` to `mkdir` because you create just one directory
> Remove -p argument for prebuild task

- src/_data.json
- src/index.ejs
took base concept from Robert's PR https://github.com/jscraftcamp/website/pull/371
* update date & location in header
* add VI as location sponsor
* add VI address under location (linked to Google Map)
* removed Megan from team page
using Google Maps directly is possible
but problematic due to new GDPR
regulations
> update date & location

- participants/olaf_merkert.json
> add registration data for Olaf Merkert

- participants/joern_bernhardt.json
> Add Jörn Bernhardt to the list of participants

- participants/tanner_hoisington.json
> adds Tanner Hoisington to participants

- participants/philipp_renoth.json
> participants: fix philipp_renoth.json is coming

- participants/frank_mueller.json
> add participant

- participants/alessandro_vizin.json
> Modify participation dates and Add a tag

- README.md
- package.json
- when developing let me (developer) control which browser to use and restarting it, not the `npm start` script
- improve README a bit
> No automatic browser start on `npm start`

- participants/petar_milutinovic.json
> Added personal file for the participation in JS Camp 2018

- participants/julian_jaser.json
> added julian_jaser.json for registration

- participants/vannsl.json
> add participant vannsl

- src/index.ejs
The impression link still links to photos from 2017 but we have photos from 2018 already...!
> Fix link to 2018 photos

- src/css/main.css
This year's color is a bit lighter, therefore I have a couple changes, that would be nice to get review/fix/opinions on
> Adjust main color

- participants/floatec.json
> added participant floatec

- participants/ahmed_farahat.json
> adding Ahmed Farahat to participants

- participants/christopher_brinker.json
> Add christopher_brinker.json as participant

- participants/paul_janicki.json
- src/registration.ejs
- test/participants.js
> Make `tags` in participants.json required

- participants/_template.json
This adds the twitter field. I'd prefer `null` as default value, but went with the empty string `""` for consistency reasons.
Fixes #696
> Participant template `twitter` field

- participants/manuel_ernst.json
> Add manuel_ernst.json

- participants/celestine_auburger.json
> feat(participant): add celestine

- participants/thorsten_brunzendorf.json
> add thorsten to participants

- participants/carsten_lamm.json
> Add Carsten to participants

- participants/markus_knittig.json
> Add Markus Knittig as participants

- src/index.ejs
It makes sense to have the new name "Angular" on the website, since "AngularJS" is the older, deprecated version 1.x
https://angular.io vs https://angularjs.org
> Prefer "Angular" name over "AngularJS"

- netlify.toml
Changed the configuration for netlify:
* ignore the gh-pages branch
* run the build-storybook script and include it in Gatsby (just as static resources)
more details/documentation: https://docs.netlify.com/configure-builds/file-based-configuration/
Part of #861 
The resulting page should be available at 🎈 
https://deploy-preview-872--jscraftcamp.netlify.com/storybook
=> So you just need to add the `/storybook` path to the preview-url 🎉
> Build storybook on netlify preview

- gatsby-config.js
- src/components/intro/intro.js
After one year of covid pandemia we need to try a new start, and at least update the year on our web page.
> replace 2020 with 2021

- src/components/intro/intro.js
Cleanup: I guess we can remove redundant, obsolete text:
~The Orga team has kicked off the effort for the next steps to bring this years event into fruition~
> remove redundant headline

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/registration-tests.yml
- participants/cristobal_heiss.json
- participants/marcoemrich.json
- src/pages/register.js
`master` changed to `main` recently and we should change the instructions and templates accordingly
> fix: Use main as default branch name

- participants/yogan.json
> Add yogan to participants

- participants/heinzster.json
> add heinz to list of participants

- participants/alex_wiesinger.json
> Add Alex Wiesinger to participants

- participants/msh.json
- [ x] My pull request contains a JSON file `$name_or_nickname.json`    
- [x ] The JSON file follows the template at [https://github.com/jscraftcamp/website/blob/main/participants/_template.json](https://jscraftcamp.org/register/) and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x ] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp …
> add registration file for msh

- _templates/component/new/component.js.ejs.t
- _templates/component/new/component.module.scss.ejs.t
- _templates/component/new/component.story.js.ejs.t
- _templates/component/new/index.js.ejs.t
- _templates/component/new/prompt.js
Added missing `hygen` files (still referred to by the readme).
...making it easier to create `components` in the current design:
Creating a new `Team` **section**:
```
yarn hygen component new --componentKind sections --name team 
```
Any basic component:
```
yarn hygen component new --componentKind components --name team 
```
---
Originally created by (kudos goes to)  @michaelzoidl
> Add missing hygen template files

- participants/mlgr.json
> Register michael for JSCC 2022

- participants/tsgn.json
> Add tsgn to participants

- src/sections/covid-rules/covid-rules.js
Sebastian wrote:
> Legal info regarding testing procedure: we are safe if we prolongue the test to 48 hrs, so everyone can test on Wednesday.
https://jscraftcamp.slack.com/archives/C035P8E9Q80/p1654700331524409
> adapt wording to reflect max 48h certificate due to bank holiday

- participants/jewgenij_steinhart.json
> add participant jeff

- participants/joern_bernhardt.json
> Register Jörn as participant

- participants/mario_volke.json
> Add Mario Volke to participants

- participants/bernd.json
> Add Bernd to participants

- participants/dan.json
> add dan to participants

- src/routes/registration/+page.svelte
This is a minor QoL improvement so participants don't have to search around the website to find the relevant GitHub repo.
> feat: Add repo link on registration page

- participants/mlgr.json
> chore: Add michael as a participant

- participants/manuel.json
> add mernst

- participants/dgrabla.json
> chore: add dgrabla as participant

- participants/deniz_schmidt.json
> Add Deniz Schmidt to participants

- participants/theabdolah.json
> Add The Abdolah to participants

- participants/clemens.json
- participants/jonas_kaltenbach.json
> Add Jonas and Clemens to participants

- participants/christian_waldmann.json
> Add Christian Waldmann to participants.

- participants/derdaani.json
> Add derdaani to participants.

- participants/vanderlei_silva.json
> add Vanderlei to participants

- participants/artur_ptaszek.json
> feat: registration Artur Ptaszek

- participants/_template.json
- participants/alexander_wiesinger.json
- participants/bernd.json
- participants/brigitte-jellinek.json
- participants/christian_waldmann.json
- participants/fabian_biberger.json
- participants/jonas_kaltenbach.json
- participants/marco.json
- participants/matthias_stemmler.json
- participants/mlgr.json
- participants/philip-saa.json
- participants/theabdolah.json
- src/lib/participants/participant-schema.ts
- src/routes/registration/+page.svelte
I am submitting this PR so that our T-shirt template includes `3XL shirt sizes`. Currently, the template only offers sizes up to 2XL, which may exclude heavier participants, including myself. My hope is that by adding 3XL sizes, participants will get a shirt that they can actually wear. The includes updating event registration page, the participant json template and the schema for the json validation. This change demonstrates our commitment to inclusivity and enhances the overall participant experience.
Thank you for your consideration.
> Add 3XL T-Shirt Size option

- participants/yinyin_wuhanke.json
> add Yin as participant

- participants/pavlo_denysiuk.json
> Add Pavlo Denysiuk as participant

- participants/tobias_oettl.json
> added tobias_oettl.json

- participants/daniel_hilpoltsteiner.json
> add daniel hilpoltsteiner to participants

- .github/PULL_REQUEST_TEMPLATE.md
- participants/larisa_antsifrova.json
> Adding participant: Larisa Antsifrova

- participants/bene_koehler.json
> Add: bene_koehler.json

- participants/gustaf.json
> Add participant Gustaf

- src/routes/registration/+page.svelte
I got the feedback,  that not everybody is comfortable to enter private/personal data in the Repo. This PR adds an info box that all personal data can be sent privately to one of the organizers.
> Add personal data info box

- participants/timidak.json
> add registration for timidak

- participants/dmitrii_forofontov.json
> feat: add Dmitrii Forofontov

- participants/jfhr.json
> add participants/jfhr.json

- participants/matthias_schmid.json
> added matthias_schmid.json

- participants/ahmad_soliman.json
> register ahmad soliman into participants folder

- src/lib/participants/Participant.svelte
I would like to supply a small fix, as my contents on the detail page do not wrap nicely.
Sorry for the hassle, a local fork of an old version of the website had some non pushed commits ...
> fix(Participants): fix accidental content overflow

- participants/axt_konstantin.json
> feat: add konstantin axt

- participants/larisa.json
> Add Larisa to the participants

- participants/jennifer_falkenstein.json
> feat: add jennifer to participants

- participants/dkbob.json
> feat: added dkbob to participants

- participants/michael_zoidl.json
> Add Michael Zoidl to participants

- participants/julio_lopez.json
> Add julio lopez to the jscraftcamp

- participants/felix_fischer.json
> feat(): add felix fischer

- src/routes/participants/stats/+page.server.ts
hetzner cloud, TNG, and inovex were added incorrectly
> Stats fix sponsor list

- participants/salome_wick.json
> add salome to participants

- participants/timmyjs.json
> Add timmyjs to participants

- participants/michael_mannseicher.json
> chore: add registration

- participants/savas.json
> add savas to participants

- participants/git-commit.json
> Add git-commit to participants

- participants/fii.json
> chore: add fii as a participant

- src/lib/participants/Participant.svelte
While checking my registration, I noticed that social media buttons are not displayed if the only social media is linkedin. This PR fixes that.
> fix: add linkedin as a valid social network

- participants/_template.json
- src/routes/registration/+page.svelte
- Fix the date (use 2024) and make it easier readable.
- Add the things I missed when reading the registration page (info about JSONC and direct link to start PR).
> Small adjustments (better registration instructions, I hope)

- participants/crowlkats.json
> add crowlKats to participants

- participants/marvinh.json
> Add marvin hagemeister to participants

- participants/reed.json
> add reed to participants

- participants/bastian_gebhardt.json
> Add Bastian Gebhardt to participants

- participants/_sergej-paris.json
> Add myself as a participant 2024

- participants/nidhal_labidi.json
> Chore: add  Nidhal Labidi as a participant

- participants/nickkriesing.json
- [ x] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
> Add nickkriesing.json

- src/lib/participants/Participant.svelte
This pull request fixes an issue where a participant's card overflows if it has 5 or more social media logos displayed.
**Fix:**
Added flex-wrap: wrap; on the div with class 'socials'.
> Fix: Participant Card Logo overflows when 5+ links are present

- participants/matthew_odonnell.json
> Add matthew_odonnell.json

- participants/dnnr.json
> Add dnnr to participants

- src/lib/participants/participant-schema.ts
We currently allow empty strings in the list of tags. This should not be possible: The tag list should only contain non-empty strings.
Be aware, this will break the PR / registration for #1941 (@IObert)
> fix: Disallow empty strings in tags

- participants/lukas_frey.json
> Add lukas_frey.json

- participants/gustaf.json
> chore: register Gustaf as a participant

- participants/jesusreal.json
> Add participant file

- src/lib/sponsoring/sponsors-2024/is-sponsor.ts
We had this in the stats:
...and we want this:
> Change name for TNG sponsoring

- participants/christoph.json
> Add christoph.json

- participants/magnus.json
> feat: add participants/magnus.json

- participants/pmbanugo.json
> Create pmbanugo.json participant

- participants/lars_gregori.json
> add lars_gregori.json

- src/lib/layout/Logo.svelte
I just noticed this strange copy & paste behavior that adds the string "2016". I thought we can, at least, update it to 2024 😁
https://github.com/jscraftcamp/website/assets/1873245/6a4cd93e-ef89-402a-8008-c4d783a300f9
> fix: Update Logo.svelte to display correct year

- src/lib/layout/Logo.svelte
Reverts jscraftcamp/website#2014
Try hovering over the different colors of the main logo. The text that was changed actually shows the previous years. We need to fix this in a different way or the orange color will be incorrectly set to 2024.
https://github.com/jscraftcamp/website/assets/1767865/205a016c-279d-4640-832d-d82bb711ac94
> Revert "fix: Update Logo.svelte to display correct year"

- participants/gabriel-b.json
> Add Gabriel as a participant

- participants/bitcloud
- participants/bitcloud.json
> Add bitcloud as a participant

- participants/pavlo_grosse.json
> Add Pavlo Grosse to participants

- participants/clemens.json
I would like to register Clemens for JS CraftCamp.
> Add clemens

- src/lib/participants/participants.ts
- src/lib/participants/statistics.ts
- src/lib/sponsoring/sponsors-2024/is-sponsor.ts
Some sponsors did not have a 👑 next to their employee count in `/participants/stats`. This should fix it.
> chore: Correct sponsor names / keys

- participants/gustaf.json
In my original commit my file accidentally said I can only participate on friday. This is not the case I would love to be there on both days.
> chore: fix when Gustaf can attend

- src/routes/+page.svelte
The "When" part was wrong.
Current:
Corrected:
> Fix typo in "When" box for registration

- src/routes/+page.svelte
Sorry, we made a quick fix last year to close the registration when we had too many participants registered. This PR reverts this change.
> fix: Open registration as we are not full YET

- participants/phaus.json
- [ x ] My pull request contains a JSON file `$name_or_nickname.json`
- [ x ] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
- [ x ] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ x ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count …
> adding phaus as participant

- participants/yogan.json
> Add yogan as participant

- participants/pmbanugo.json
> Add participant pmbanugo.json

- participants/clemens.json
> Add Clemens as participant

- participants/oliver.json
> Fix typo in participant description.

- participants/julian.json
> feat: add julian s. as participant

- participants/olesia.json
> feat: add olesia as participant

- participants/gustaf.json
> chore: register Gustaf as a participants

- src/lib/participants/participant-schema.ts
Fixes #2203 
GitHub account name can have a `-` at the end as @ghost91- has proven
> Allow dash at the end of GitHub account name

- participants/mstingl.json
> feat: add participant mstingl

- src/lib/participants/statistics.ts
- src/routes/+page.svelte
- src/routes/participants/stats/+page.svelte
Show the amount of vegan and vegetarian vs no food preference people on the stats page.
Main page could show negative numbers for seats left, which shouldn't be the case.
> Improve stats and fix max seats
