jscraftcamp/website

- README.md
> link to page

- participants/balsa_bojic.json
[ ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
[ ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
[ ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Registration request - Balsa Bojic

- package.json
- participants/wolfram_kriesing.json
- src/css/main.css
- src/participants.ejs
- test/participants.js
I made
- the number of tags and their length less constraining, so it's not so hard to fail there
- made the site render properly with any number of tags
- fill in my data :)
> Less constraining signup

- package.json
- participants/wolfram_kriesing.json
- src/css/main.css
- src/img/jscc-logo-without-text.svg
- src/index.ejs
- src/participants.ejs
- test/participants.js
this adds the logo on the page, and looks like this
> Add logo on the website

- package.json
- participants/wolfram_kriesing.json
- src/css/main.css
- src/img/jscc-logo-without-text.svg
- src/index.ejs
- src/participants.ejs
- test/participants.js
> Text for wolfram

- src/index.ejs
The Linked-In Link of Pierluigi opens in the same window - thats annoying.
I added a 'target="_blank"' to make it open in a new tab.
> Added 'target=blank to linkedLink of pierluigi

- participants/vanessa_boehner.json
[x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when` and `what_is_my_connection_to_javascript` `    
> adds json file for vanessa boehner participant

- participants/christoph_wiechert.json
> Added: participants/christoph_wiechert.json

- participants/simon_frost.json
> Add Simon Frost to participants

- participants/christian_justus.json
> Add Christian Justus to participants

- participants/david_losert.json
> Added David Losert as participant

- participants/stefanie_hasler.json
[x ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
[x ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
[x ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> add stefanie to participants

- participants/_template.json
- scripts/concat-json.js
@cko : Is there a reason you deleted the _template.json after @wolframkriesing added it?
If so: It's still linked within the PR-Template - we should either add it again with this PR or delete the Link from the PR-Template.
> Added _template-Json again as it was (accidently?) deleted

- participants/ana_carraca.json
> Added Ana Carraca to participants

- participants/dejan_ranisavljevic.json
[x] My Pull Request contains a json file $firstname_$lastname.json or $nickname.json
[x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields name, tags, when, what_is_my_connection_to_javascript and what_can_i_contribute_to_js_craftcamp
> Register for JS CraftCamp

- participants/invited/joern_bernhardt.json
[+] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
[+] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
[+] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Update my info + tshirt size :)

- participants/maruf_siddiqui.json
[✓] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`
[✓] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript`
[✓] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Add maruf siddiqui to participant list

- participants/lukas_taegert.json
[ x ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
[ x ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
[ x ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Add Lukas Taegert to participants

- participants/ricardo_borillo.json
[ x] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
[ x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
[x ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> JS CraftCamp registration

- participants/mario_volke.json
> Add Mario Volke to participants

- participants/christian_ranz.json
[X] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
[X] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
[X] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Add participant Christian Ranz

- participants/jonathan_häberle.json
> Add Jonathan Häberle to the participants

- .github/PULL_REQUEST_TEMPLATE.md
> Use real checkboxes in pull request template

- participants/marco_schaefer.json
> add registration profile for marco

- participants/alexander_reelsen.json
> Add Alexander Reelsen to participants

- participants/sebastian_graef.json
> Add Sebastian Graef to participants

- participants/ben_bieler.json
> Add benbieler

- participants/dirk_gomez.json
> add Dirk's registration

- participants/max_kleucker.json
> Registration Max Kleucker

- participants/robert_prediger.json
> Add Robert Prediger

- participants/walter_kammergruber.json
> Add Walter Kammergruber

- participants/lukas_jakob.json
> Participant Lukas Jakob added.

- participants/simon_wicki.json
> add simon wicki participant

- participants/christian_koch.json
> added Christian Koch

- participants/vincent_wagner.json
> added participant Vincent Wagner

- participants/ali_churcher.json
- [ x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute_to_js_craftcamp`    
> Added a new participants json file for Ali Churcher registration.

- src/registration.ejs
> registration: add note that it's free

- participants/stefan_siegl.json
> Add Stefan Siegl to list of participants

- participants/sebastian_herrmann.json
> add Sebastian Herrmann to list of participants

- participants/Michael_Ohr.json
+ added Michael Ohr as participant
> Add Michael Ohr

- participants/philip_saa.json
> Philip Saa Registration

- participants/christine_koppelt.json
> participants: add text for christine

- scripts/concat-json.js
> participant page: sort alphabetically

- src/css/main.css
still very hacky, but looks slightly better
> participants: move photos slightly upwards

- participants/jan_unger.json
> Registration Jan Unger

- participants/thomas_mayrhofer.json
> Register Thomas Mayrhofer.

- participants/julian_kempff.json
> Adds julian kempff as a participant

- participants/philipp_grimm
- participants/philipp_grimm.json
> Registration: philipp grimm

- participants/christoph_neuroth.json
> Register Christoph Neuroth

- participants/dali_zheng.json
> Add Dali Zheng

- participants/sebastian_sauer.json
> Add Sebastian Sauer to participants

- participants/michael_zoidl.json
> Add Michael Zoidl to participants

- participants/frank_deberle.json
> Add Frank Deberle to participants

- participants/sebastian_slomski.json
I did not run the tests as I'm on vacation and I don't want to download all those deps on edge. So it is "Works on my machine".
> Added Sebastian Slomski to participants

- participants/dominik_heller.json
[x] My Pull Request contains a json file $firstname_$lastname.json or $nickname.json
[x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields name, tags, when, what_is_my_connection_to_javascript and what_can_i_contribute_to_js_craftcamp
> Add Dominik Heller to participants

- .github/PULL_REQUEST_TEMPLATE.md
Small typo in template `what_can_i_contribute_to_js_craftcamp` => `what_can_i_contribute`
> fix pull request template

- participants/jan_schmidle.json
> Added Jan Schmidle to participants

- participants/fabian_holzer.json
> Add Fabian Holzer to participants

- participants/julie_ng.json
> Add Julie Ng to participants

- participants/andreas_jaegle.json
> @ajaegle taking part

- participants/patrick_dubroy.json
> Add myself as a participant.

- participants/vitaliy_stepanyuk.json
> New participant

- participants/georg_schmidl.json
> Add Georg Schmidl to participants

- participants/florian_loretan.json
> Registration for Florian Loretan

- participants/holger_schulz.json
> Added Holger Schulz to participants

- participants/andreas_harter.json
> Add aharter to the list of participants

- participants/brigitte_jellinek.json
- [X ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [ X] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ X] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Registering Brigitte Jellinek

- participants/brigitte_jellinek.json
twitter profile pic does not seem to work
> FIX: use github profile pic

- participants/florian_benz.json
> Add Florian Benz to participants

- participants/stefan_rohe.json
> Request for Participation

- participants/markus_tacker.json
> Registration

- participants/steffen_lindner.json
> Add Steffen Lindner to participants

- participants/christian-waldmann.json
> Add Christian Waldmann to participants

- participants/christian-waldmann.json
- [ x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Update christian waldmann

- participants/fernando_giovanini.json
> Fernando is participating!

- participants/chris_mair.json
> registration Chris Mair

- participants/sebastian_rehm.json
> Registration of Sebastian Rehm

- participants/vladimir_ivanov.json
- [ X ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [ X ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ X ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> add vladimir_ivanov.json

- participants/carlo_jeske.json
> [participiants] added carlo jeske

- package.json
- src/js/tshirt-sizes.js
- src/participants.ejs
- test/tshirt-sizes.js
This makes the participants page show the shirts stats, which we need e.g. for ordering them, when going to this URL http://jscraftcamp.org/participants#list-tshirt-sizes (the hash makes it show).
/cc @lowsky ... I invited you, wasnt able to add you to the organization though :(
> T-Shirt sizes

- participants/invited/balsa_bojic.json
> T-Shirt size added

- participants/daniel_warkentin.json
> Added Daniel Warkentin to participants.

- participants/sebastian_wiesner.json
> Fill my registration

- participants/francois_godet.json
> Add Francois Godet to participants

- participants/dimitry_polivaev.json
> Dimitry Polivaev

- participants/jonathan_prince.json
> add jonathan prince

- participants/johannes_hauf.json
> Registration for Johannes Hauf

- participants/gaganjot_singh.json
> Gaganjot Singh added to participants

- participants/stephan_stamm.json
> request to participate

- participants/tobias_reuleaux.json
- [x ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
> added tobias_reuleaux.json to participants

- participants/erich_lehmann.json
- participants/jonathan_häberle.json
> Added Erich Lehmann

- participants/david_neubauer.json
> Unfortunately I'm not able to attend on sunday

- participants/thomas_mayrhofer.json
> I won't be joining on sunday due to my half marathon.

- participants/amit_sama.json
> added amit_sama.json to participants

- participants/jewgenij_steinhart.json
> please consider my registration :)

- participants/florian_loretan.json
Unfortunately, I can only attend on Sunday. This pull request updates my registration accordingly.
> Update attendance for Florian Loretan.

- participants/dimitrios_tosidis.json
> adding participant

- participants/ahmed_hassanein.json
> add Ahmed Hassanein

- participants/dominik_mayer.json
> Added participant info.

- participants/invited/franziska_hinkelmann.json
I would like to update my registration for JS CraftCamp.
> Update info and attendance for fhinkel

- src/_layout.ejs
- src/index.ejs
As I read on the chat we have decided on a date, right?
If so review (and maybe merge) please.
> Add the date of the upcoming JSCraftCamp. 1/X

- README.md
- src/_data.json
- src/_footer.ejs
- src/_layout.ejs
- src/_navigation.ejs
- src/css/main.css
- src/index.ejs
includes the code of #177 too, which means if u merge this one #177 will be merged too
this PR does:
> Make some data reusable 2/X

- src/_layout.ejs
- src/css/main.css
- src/index.ejs
The signup form is functional. The styling could be ... improved. Maybe someone with better design skills than me, could improve the placement of the newsletter signup form.
> Add mailchimp newsletter reg form with basic styling

- src/_data.json
- src/_footer.ejs
- src/_navigation.ejs
- src/css/main.css
- src/index.ejs
- src/registration.ejs
I styled the site with new color for 2017. What do you think?
And I embedded the "programmed logo" (from https://jscraftcamp.github.io/logo/src/ code is at https://github.com/jscraftcamp/logo)
I would be happy if any materialized-design expert could improve this code https://github.com/jscraftcamp/website/commit/89c5ff41f05d969d05e888ecdba8cd4e40de96e4 (can also be done later) ...
> New color for 2017, orange!

- src/index.ejs
I changed the E-Mail Text to be a bit more explaining what a subscribe actually will do.
> Changed E-Mail List Text to be a bit more explaining

- src/css/main.css
- src/index.ejs
See screens below
before:
after:
> Mobile improvements

- src/_data.json
- src/sponsoring.ejs
Please do proof reading, and changes as fit
> add first  version of sponsoring page

- src/css/main.css
- src/imprint.md
- src/index.ejs
Add class flow-text (from materialize design) to most text elements (p-Tags).
*  some of the text have been too small, hard to read.
*  this also helps with consistency, because it now uses the correct font (Roboto) from materialze design
* the class is designed with moible in mind and scales down as fit.
Also made some minor improvements to the imprint page
> small styling improvements

- src/_data.json
- src/_navigation.ejs
- src/css/main.css
- src/index.ejs
I made the registration/subscribe call to action a bit more prominent.
See img
> Highlight the signup more

- src/index.ejs
Triggered by the nice way of asking and the request for explanation by  https://twitter.com/Argorak/status/866283264436260865 this change tries to explain the cost for attendees.
> Explain that it is for free.

- src/index.ejs
* add new block "How to register?"
* change layout from 3 columns to 2 columns blocks
this was necessary because of the added block
to still have a balanced layout
* move Wolframs "attendance is free"-text to "How to register" block
* add explaination about the Pull Request
> Improve explaination of the registration proccess

- src/index.ejs
* Made introduction session 30 minutes longer
* Made Event on Saturday until 18
> Adjusted time schedule:

- src/index.ejs
* add header and name
* add twitter handle and linked it back to twitter
> anounce Tobias as our Facilitator on the start page

- src/sponsoring.ejs
after checking the costs for beverages of last year
> adapt price for beverages

- participants/joern_bernhardt.json
You should really have this guy on your list.
> Add Joern Bernhardt to list of participants

- participants/andreas_jaegle.json
> @ajaegle participating again

- participants/fabian_matern.json
> My registration (fabian matern)

- participants/martin_lechner.json
> Added Martin Lechner.

- participants/lars_gregori.json
> add participant Lars Gregori

- participants/radu_baranga.json
- src/sponsoring.ejs
> add registration json

- participants/andreas_neumann.json
> participant added: 'Andreas Neumann'

- participants/axel_hodler.json
> add @axelhodler to participants

- participants/frank_blendinger.json
> add Frank Blendinger to participants

- participants/markus_knittig.json
- [ X] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [ X] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [X ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Added registration for 'Markus Knittig'

- participants/ana_carraca.json
> add Ana Carraca to participants

- participants/carsten_lamm.json
> Add carsten_lamm to participants

- participants/andreas_harter.json
> Add Andreas Harter to participants for #jscc17

- participants/michael_jaser.json
> Add Michael Jaser

- participants/ruben_straube.json
> Add Ruben Straube

- participants/michael_ohr.json
Unfortunately, I can only attend on Saturday this year.
> Add Michael Ohr as participant

- participants/christian_waldmann.json
> Add christian waldmann

- participants/thanh_le.json
I can only attend Saturday this time.
> Add Thanh Le as participant

- participants/florian_loretan.json
> Add Florian Loretan to participants.

- walter_kammergruber.json
> added registration for walter kammergruber

- participants/stefan_rohe.json
> apply for jscraftcamp

- participants/thomas_traenkler.json
> looking forward to the pizza fest

- participants/michael_czechowski.json
> added new passionate participant

- participants/zied_ghalleb.json
> Registered as Zied Ghalleb

- participants/jonathan_juhas.json
> Add Me (Jonathan) to participants

- participants/michael_zoidl.json
**Offtopic**
If possible: `M-XXL` :)
> Add Michael Zoidl

- participants/markus_westphal-furuya.json
> My (Markus) humble application for participation.

- participants/johann_sonntagbauer.json
> participant: johann sonntagbauer

- participants/frank_mueller.json
> Registration for JSCraftCamp

- participants/jesus_real.json
> Add myself (Jesus) as participant

- participants/brigitte_jellinek.json
> new participant: Brigitte Jellinek

- participants/paul_torka.json
> Add Paul Torka

- participants/stefanie_hasler.json
> Register Stefanie

- participants/christian_stangier.json
Hi there! I would like to register for JS CraftCamp.
> add Christian Stangier

- src/_navigation.ejs
- src/index.ejs
The gmaps API key seems to have been expired, I generated a new one. Let's see :)
> Fix map and add GitHub link

- participants/christian_hoerauf.json
- [x ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [x ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
> add christian hoerauf

- participants/andreas_scharf.json
> Add Andreas Scharf

- participants/jowe.json
> Add Johannes Weber

- participants/torsten_goerner.json
> Please register me (Torsten Goerner) for JS CraftCamp 2017. Many Thanks!

- participants/ben_bieler.json
> register-ben-bieler

- participants/nicole_rauch.json
- src/registration.ejs
-> No, it does not follow the template because the template contains an error :-) I fixed that in the other commit.
> My registration + template fix

- participants/andreas_sahle.json
Not easy to create a PR with an IPad on holidays ;)
Involved a lot of copy and paste wizardry
> Participant Andreas Sahle

- participants/sebtm.json
> Participant SebTM

- src/sponsoring.ejs
> jambit is sponsoring stickers

- participants/antonia_schmalstieg.json
> Registration antonia

- participants/balsa_bojic.json
> Participation request - Balsa Bojic

- participants/emin_bugra_saral.json
> Add Emin Bugra Saral

- participants/ahmed_farahat.json
> Registration - Ahmed Farahat

- participants/michael_gerhaeuser.json
> Add participant Michael Gerhaeuser

- participants/jonathan_prince.json
> Add Jonathan Prince to participants

- participants/anian_ziegler.json
> Participation request - Anian Ziegler

- participants/david_suilea.json
> Register - David Suilea

- participants/igor_likhomanov.json
> add Igor Likhomanov to participants

- participants/christoph_neuroth.json
> Add c089 (2017 edition)

- participants/jonas_lorenz.json
- [+] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [+] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when` and `what_is_my_connection_to_javascript`
- [+] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> register jonas lorenz

- participants/agnes_koehler.json
> register Agnes Köhler

- participants/david_voelkel.json
> added participant david völkel

- participants/adrian_menzel.json
- [ x ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [ x ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ x ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> new participant adrian_menzel

- participants/markus_edenhauser.json
> new attendee markus_edenhauser

- participants/mark_wilson.json
> Registration - Mark Wilson

- participants/sandra_zollner.json
> register Sandra Zollner

- participants/christian_ranz.json
> Register christian ranz

- participants/markus_anetsberger.json
Please note: There is no picture worth your website,
> added registration file

- participants/robert_hostlowsky.json
> register robert hostlowsky

- participants/oleksandr_fedotov.json
> looking forward to July 21!

- participants/adam_christian.json
> Register Adam Christian

- src/js/dietary-requirements.js
- src/participants.ejs
- test/dietary-requirements.js
I would like to add functionality for extracting and sorting dietary requirements to the website.
> add dietary requirements

- participants/helge_krueger.json
> Added Helge Krueger

- participants/sebtm.json
> Change participation-day

- participants/tobias_wichtrey.json
> register Tobias Wichtrey

- participants/anja_kaiser.json
> Add Anja Kaiser to participants

- participants/vincent_wagner.json
> chore: added new participant vincent wagner

- participants/wolfram_kriesing.json
I would be so glad to join ... let's see first if the tests pass ....
> Add participant: Wolfram Kriesing

- participants/dimitry_polivaev.json
> Registration Dimitry Polivaev

- participants/adrian_menzel.json
> I will be there on friday

- participants/bela_varga.json
> Participant registration.

- participants/almansourbelleh_blanco.json
- [ x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
> Almansour Belleh Blanco participation

- participants/carsten_meier.json
> add participation json

- participants/astrid_mahrla.json
> Astrid's application

- participants/irena_reitz.json
> add participation 

- participants/fabian_matern.json
as discussed with Marco Emrich I adjust my participation.
> I will only attend friday

- participants/rafael_brandmaier.json
> Add Rafael Brandmaier as participant

- participants/benjamin_bauer.json
> New registration

- participants/oliver_prater.json
- [ x ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [ x ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ x ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Add participant Oliver Prater on Saturday

- .travis.yml
- README.md
- package-lock.json
- package.json
- shell.nix
- There seem to be even more outdated packages, so I updated those.
- For optional usage: I added nixos (package manager) that allows for setting up a reproducible nodejs env
> Upgrade to latest nodejs v9 (and optionally add nixos)

- src/_data.json
- src/css/main.css
- src/index.ejs
- use the new color and
- make all links use the last year's color, so they stick out
> Adjust color scheme for 2018

- src/sponsoring.ejs
* relink sponsoring issues to 2018 issues on github
* remove sponsor names from last year
> update sponsoring page

- src/index.ejs
* remove text about jscc17
* remove Map to VI
* add "looking for location..."-text
> change main anouncement

- src/index.ejs
> add codecentric logo

- src/_data.json
- src/index.ejs
- src/sponsoring.ejs
- add register link to navi
- improve some wording
> Smaller changes, Add registration button to navigation

- participants/invited/daniel_hilpoltsteiner.json
> Daniel Hilpoltsteiner would like to participate :)

- participants/michael_zoidl.json
> Add Michael Zoidl as participant

- participants/lilia_kraft
> Adding registration for Lilia Kraft (JS CraftCamp 2018)

- participants/invited/sergii_paryzhskyi.json
> Add Sergii Paryzhskyi as a participant

- participants/willy_schott.json
> Add participant Willy Schott

- participants/christoph_hummel.json
- [ x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `tags`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
> add christoph_hummel.json

- participants/dominik_dier.json
> add registration for Dominik Dier

- participants/carsten_lamm.json
> Add Carsten Lamm to participants

- participants/stefanie_neubert.json
> add stefanie_neubert.json

- participants/felipe_salazar.json
> Add new participant Felipe Salazar

- participants/samir_caus.json
- [X ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`
> add samir participant file

- participants/marvin_altemeier.json
> Add Marvin Altemeier to participants

- participants/carlo_jeske.json
> [participants] added carlo jeske

- participants/sergei_kriger.json
- [x ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [ x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ x] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
> Sergei Kriger registration

- participants/anian_ziegler.json
> register anian ziegler

- participants/andrei_bechet.json
> andrei-bechet

- package-lock.json
- participants/alessandro_vizin.json
> Alessandro vizin

- participants/martin_lechner.json
> Register Martin Lechner

- participants/radu_baranga.json
> Create  radu_baranga.json

- participants/philip_saa.json
Glad to be attending again. Gotta secure lodging, but I'm really looking forward to it.
> Create Philip Saa JSON

- participants/_template.json
- src/css/main.css
- src/participants.ejs
- src/registration.ejs
- show the tags of the participants on the participants page (see img)
> Render the tags and make them show on hover.

- participants/brigitte_jellinek.json
- [X ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [X ] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [X ] If I can't attend, I will either send another Pull Request removing my json file or an E-Mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [X ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
> Brigitte Jellinek is taking part

- participants/andreas_scharf.json
> Sign up @andys8

- participants/astrid_mahrla.json
> registration for astrid

- participants/peter_halasz.json
> Peter Halasz registration

- participants/deborah_koepfer.json
> Registration Deborah Köpfer

- participants/wolfram_kriesing.json
> Sign up Wolfram Kriesing

- participants/jonathan_prince.json
> registration Jonathan Prince

- participants/anna_gruber.json
> Added Anna Gruber as a participant

- participants/ulf_biallas.json
> Add Ulf B as participant

- participants/ion_petrache.json
> Add myself as participant

- participants/yves_hoppe.json
> Registration Yves Hoppe

- participants/claudia_vieira.json
> Registration Claudia Vieira

- participants/andrej_schneider.json
> Registration Andrej Schneider

- participants/markus_ziller.json
> Add participant markus ziller

- participants/stefan_hanke.json
> add participant stefan hanke

- participants/markus_schmidtner.json
> Markus Schmidtner would like to participate

- participants/ines_akrap.json
> Ines Akrap registration

- participants/shady_botros.json
> Register shady botros

- participants/johannes_weber.json
> Add participant: Johannes Weber

- participants/martin_duerre.json
> Anmeldung Martin Duerre

- participants/karthikeyan_palaniswamy.json
> Add participant: Karthikeyan Palaniswamy

- participants/marcel_donges.json
- participants/philipp_bartels.json
> Register Philipp and Marcel

- participants/irena_reitz.json
> Registration Irena Reitz

- participants/ann-kristin_krappe.json
> add participant Ann-Kristin Krappe

- participants/celestine_auburger.json
> Register Celestine Auburger

- participants/marziye_tanha.json
> add marziye tanha

- participants/markus_heer.json
> Add Markus Heer

- participants/oleksandr_fedotov.json
> Add Oleksandr Fedotov to participants list

- participants/markus_heer.json
Sadly, because of work, i won't be able to make it on friday, but i would love to join you on saturday!
> update markus heer (remove friday)

- participants/tobi_reiss.json
> register tobi

- participants/marco_emrich.json
> add participant Marco Emrich

- participants/maruf_siddiqui.json
> Add maruf_siddiqui.json

- participants/stefan_sauterleute.json
> Register sauterleute

- participants/eva_gyomrey.json
- [x ] My Pull Request contains a json file `$firstname_$lastname.json` or `$nickname.json`    
- [ x] The json file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
> Add new participant Eva Gyomrey

- src/_data.json
I would like to register for JS CraftCamp... later, but first update the page title so I can share it on slack and twitter
> update page title for head title tag

- package-lock.json
- package.json
They accepted my security patch - yeah :)
> switch back to offical harp repo

- .travis.yml
- package-lock.json
- package.json
- shell.nix
- src/_navigation.ejs
- src/css/main.css
- src/index.ejs
I had broken the mobile UI, this fixes it again.
The logo did NOT scale down, so it overlayed the screen pretty ugly ...
> Improve mobile UI

- src/sponsoring.ejs
The links for Money 100€ and Money 500€ interchanged
> Fix links to sponsoring money tickets

- .github/PULL_REQUEST_TEMPLATE.md
I am not sure if this is enough of consent or if we need something else.
Unfortunately I did not write enough in #583 
Otherwise this closes #583
> More consent required for registering

- participants/_template.json
- test/participants.js
These are the updated tests that will run for the 2019 participants.json files.
> Adjust tests for 2019 registration

- src/css/main.css
- src/theteam.ejs
on the team's page can be improved: http://jscraftcamp.org/theteam
Images were not aligned vertically.
> Update main.css for team page

- participants/wolfram_kriesing.json
> Registering Wolfram Kriesing

- participants/jaga_santagostino.json
> registering jaga santagostino

- participants/philip_saa.json
> Phlip Saa #jscc19 registration

- participants/markus_tacker.json
> Register myself

- participants/joern_bernhardt.json
Signed-off-by: Joern Bernhardt <joern.bernhardt@googlemail.com>
- Unfortunately not
> Add Jörn to the list of participants

- participants/olaf_merkert.json
> register Olaf Merkert

- participants/lewis_coleman.json
- [-] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [-] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [-] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [-] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [-] I agree that photos and videos might be taken and published (e.g. …
> registration for Lewis Coleman

- participants/daniel_weiß.json
- [ X ] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [ X ] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ X ] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ X ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [ X ] I agree that photos and videos might be taken and …
> registration of daniel weiß 🥳

- participants/paul_janicki.json
> Register Paul Janicki

- src/_data.json
- src/theteam.ejs
> Update team page

- participants/gabriele_lippi.json
- [ x ] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [ x ] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ x ] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ x ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [ x ] I agree that photos and videos might be taken and …
> Add Gabriele Lippi to partecipants

- participants/agnes_koehler.json
> Add AgnesKoehler as participant

- participants/ion_petrache.json
- [ Y] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [Y] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [Y] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [Y] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [Y] I agree that photos and videos might be taken and published (e.g. …
> add participant - Ion Petrache

- participants/carlo_jeske.json
> [participant] added carlo jeske

- .editorconfig
> style(editorconfig): add rule for .js files

- participants/thomas_kirst.json
> Registration Thomas Kirst

- participants/sergii_paryzhskyi.json
> Add a new participant - Sergii Paryzhskyi

- participants/alfredo_fernandez.json
> Add Alfredo Fernandez to participants

- participants/michael_gerhaeuser.json
> Add Michael as participant

- participants/anian_ziegler.json
Signed-off-by: AnianZ <a.ziegler@cioplenu.de>
> participation request anian ziegler

- src/registration.ejs
I've noticed some missing/misleading information about dietary requirements on the registration page and I've tried to clarify them.
> Update registration page, description of registration object fields

- src/index.ejs
* update and re-enable schedule
* fix &amp; bugs
* update sponsors and issues
> add Schedule for 2019

- participants/simon_hofmann.json
> Add myself to list of participants

- participants/tilman_adler.json
- src/participants.ejs
> Registration Tilman Adler and Fix potential XSS vuln

- participants/markus_tacker.json
- src/participants.ejs
- src/registration.ejs
- test/participants.js
Fixes #617.
This renders the provided Twitter handle like this:
> feat: add ability to provide twitter handle

- participants/paul_janicki.json
I would like to add more information to my registration object
> Update information for Paul Janicki

- participants/sven_assmann.json
> put me on the participants list

- participants/berit_haak.json
> Add new participant file for Berit Haak

- participants/jan_schmidle.json
> jan schmidle wants to come as well

- participants/david_voelkel.json
> added david_voelkel.json

- participants/andreas_sahle.json
This will be my birthday present to me, I was born one year after the first moon landing.
> Signup Andreas Sahle for #jscc19

- participants/dejan_ranisavljevic.json
> Add dejan_ranisavljevic.json

- participants/goeker_acar.json
> Goeker Acar wants to join the camp

- participants/goeker_acar.json
> Twitter has been removed from goeker_acar.json

- participants/daniel_bolivar.json
> Add a new participant - Daniel Bolivar

- participants/paul_torka.json
> Register Paul Torka

- participants/thomas_traenkler.json
> Registration of Thomas Tränkler

- participants/rasid_redzic.json
> Add new participant - Rasid Redzic

- participants/alexander_hoffmann.json
> new participant added

- participants/sepehr_lajevardi.json
> Register Sepehr Lajevardi.

- participants/michael_hoffmann.json
> Added michael_hoffmann.json

- src/index.ejs
suggested by @Narigo
also improved layout a bit (e.g. put Facilitation above Schedule...)
> add Note about session notes repo

- src/css/main.css
the layout was unstable, setting it to a fixed size is much better
maybe next step: get rid of mouseover and show tags all the time (also better on mobile)
> improve css for participants

- participants/jake_runzer.json
> Register Jake Runzer

- participants/Alaeddin_Abugrara.json
add json file via upload
- [ Y] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [ Y] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [Y ] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [Y ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [Y ] I agree that photos and videos might …
> register Aladin Abugrara

- participants/thomas_lutzeyer.json
> Register Thomas Lutzeyer

- participants/deirdre_bringas.json
> Register Deirdre Bringas

- participants/christian_waldmann.json
> registration christian waldmann

- participants/sebastian_londono.json
> Registered Sebastian Londono

- participants/andreas_scharf.json
> Add participant @andys8

- participants/sebastian_eck.json
> register sebastian eck

- participants/philip_saa.json
Updated tags, connection, contribution, and twitter.
> Updated tags, connection, contribution, and twitter.

- participants/jonatan_juhas.json
> Add IgnusG (me) as a participant

- participants/markus_beckert.json
> Added Markus Beckert

- participants/willy_schott.json
> Registration for Willy Schott

- participants/ugurcan_sengit.json
> Add Ugurcan Sengit as a participant

- participants/sergii_kudriavtsev.json
> registraion for Sergii Kudriavtsev

- participants/sai_maddali.json
> Add participant Sai Sasidhar Maddali

- participants/christoph_hummel.json
> add christoph hummel

- participants/deborah_koepfer.json
> add deborah_koepfer.json

- participants/rasid_redzic.json
> Change property for rasid_redzic.json => saturday: true

- participants/djavan_arrigone.json
- [x ] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [x ] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x ] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [x ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [x ] I agree that photos and videos might be taken and published …
> Added my registration

- participants/brigitte_jellinek.json
> Brigitte nimmt teil

- participants/michael_leimstaedtner.json
- [ ✓] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [ ✓] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ ✓] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ ✓] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [ ✓] I agree that photos and videos might be taken and published …
> Add michael_leimstaedtner.json to the "participants" directory.

- participants/michael_hoffmann.json
> Michael Hoffmann can only attend on Saturday

- participants/henry.json
> Add Henry to participants

- participants/alexander_friedl.json
> add Alexander Friedl as participant

- package-lock.json
- participants/bachir_mehemmel.json
> Add my Bachir Mehemmel to participants

- participants/michael_gural.json
> Register Michael Gural

- participants/tobias_gutmann.json
> Add Tobias Gutmann to participants

- participants/frank_mueller.json
> Registration Frank Müller

- participants/thomas_tasler.json
> [participant] add thomas tasler

- participants/andreas_jadrin.json
> Add jambit employee Andreas Jadrin.

- src/participants.ejs
... and logs to console in browser
implements #740
> calculate number of t-shirts by sizes

- participants/carine_hammes.json
> add Carine Participant

- participants/markus_schmidtner.json
- [x ] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [x ] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x ] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [x ] I agree that photos and videos might be taken and published …
> Create Registration for Markus Schmidtner

- participants/andreas_kottre.json
> add participant Andreas Kottre

- participants/daniel_glasemann.json
- participants/jonas_lorenz.json
> register jonas_lorenz and daniel_glasemann

- participants/felicitas_kugland.jscon
- [ ✔️] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [✔️] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ ✔️] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ ✔️] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [ ✔️] I agree that photos and videos might be taken and …
> please add feli - thank you

- participants/tobias_timm.json
> Sign up Tobias

- participants/daniele_dematteo.json
> Signup Daniele De Matteo

- participants/felicitas_kugland.json
- test/participants.js
> Make sure all participant's files are JSON

- participants/florian_seif.json
- [ x] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [ x] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [ x] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [ x] I agree that photos and videos might be taken and published …
> registration florian_seif v2

- participants/sebastian_rehm.json
I would like to update my availability. Unfortunately I can't join on Saturday after all.
> Update Sebastian Rehm Saturday availability.

- participants/jurek_barth.json
> add jurek as a participant

- participants/florian_loretan.json
> Registration for Florian Loretan.

- participants/ivaylo_stoyanov.json
> Registering Ivaylo Stoyanov

- participants/marvin_hiemann.json
> registered marvin hiemann for participation

- participants/hengrui_jiang.json
- participants/philipp_krenz.json
> Add hengrui_jiang and philipp_krenz

- participants/klara_fleischmann.json
> register Klara

- participants/robert_hostlowsky.json
- [x ] My pull request contains a JSON file `$firstname_$lastname.json` or `$nickname.json`    
- [x ] The JSON file follows the template at https://github.com/jscraftcamp/website/blob/master/participants/_template.json and contains the mandatory fields `name`, `when`, `what_is_my_connection_to_javascript` and `what_can_i_contribute`    
- [x ] If I can't attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on github.
- [x ] I agree that photos and videos might be taken and published …
> Add Robert. Reaching the 110-attendees 😎

- participants/stefanie_weinaug.json
> Register Stefanie Weinaug

- src/pages/index.js
> Changed follow hint date to current year 20

- LICENSE
- README.md
- src/components/Footer.js
> mention netlify for site deploy

- src/pages/index.js
- src/pages/privacypolicy.js
- src/pages/registration.js
- src/pages/sponsoring.js
- src/pages/theteam.js
- src/pages/values.js
Inside text blocks, some links had no proper padding between other texts and did not look nice.
Tiny formatting, and "cleanup" old artefacts.
> add SEO infos, fix minor styling, do some formatting,

- gatsby-config.js
- src/_data.json
- src/pages/index.js
> add the final data 10+11 July to the website

- src/components/Facilitator.js
- src/components/Location.js
- src/components/Navigation.js
- src/components/Schedule.js
- src/components/Sponsors.js
- src/html.js
- src/pages/index.js
- src/pages/registration.js
- static/info2019.html
- moved main sections into components
- help-pull-request uses prism again
- navigation hamburger did not work on mobile - removed it
- improved registration page adressing #845
- work on page 2020, #811
> add facilitator, syntax highlighting, cosmetic💅

- .github/workflows/chromatic.yml
use caching based on hash of yarn.lock file
> add caching to github workflow build

- gatsby-config.js
- src/components/intro/intro.js
- src/components/intro/intro.module.scss
> update main page, JSCC 2022!

- src/components/intro/intro.js
Co-authored-by: lowsky <lowsky@users.noreply.github.com>
Co-authored-by: Narigo
Implements/fixed issue #1030
> feat: Update Date on main page

- .github/FUNDING.yml
- src/components/footer/footer.js
- src/components/header/header.js
- src/data.json
Let's see whether this looks good!
Changed the old link wherever I saw it to the new project board.
- Fixes #1046
> Link to new sponsoring board

- src/components/explanation/explanation.module.scss
- src/components/footer/footer.js
- src/components/footer/footer.module.scss
- src/components/header/header.module.scss
- src/components/page/page.module.scss
Should look a bit cleaner on mobile like that. I've changed the header, the footer and the explanation module. Sorry I removed the triangular design in the explanation module, but I believe it's better to have a smoother mobile experience for the site than a perfect desktop web page.
> Improve mobile view

- .storybook/main.js
- package.json
- src/components/explain-sponsoring/explain-sponsoring.js
- src/components/page/page.js
- src/components/text-block/text-block.js
- src/components/typography/typography.js
- src/components/typography/typography.module.scss
- src/components/typography/typography.story.js
- src/pages/404.js
- src/pages/imprint.js
- src/pages/index.js
- src/pages/register.js
- src/pages/theteam.js
- src/pages/values.js
- yarn.lock
We had different fonts and styling on different pages.
With this PR there will be alignment on the different pages regards to the headlines.
> Simplify, align and improve typography

- gatsby-config.js
- participants/cowglow.json
- src/components/participant-card/index.js
- src/components/participant-card/participant-card-reveal.js
- src/components/participant-card/participant-card-title.js
- src/components/participant-card/participant-card.js
- src/components/participant-card/participant-card.module.scss
- src/components/participants/index.js
- src/components/participants/participants.js
- src/components/participants/participants.module.scss
- src/pages/participants.js
Created a new page for participants. Takes the contents of the participants directory. Card component has two phases, a `details` & `overview`. Toggle between the phases by clicking on the name of the participant.
Please style as you may see fit.
> Participants page

- .github/PULL_REQUEST_TEMPLATE.md
add the "I wear my mask" checkbox
> Update PULL_REQUEST_TEMPLATE.md - confirming to wear a mask+tested negative

- src/components/footer/footer.js
- src/components/header/header.js
Add a button, in the main navigation, so people find the registration.
> Add "Registration" to the navigation.

- participants/narigo.json
> Registration for Jörn

- participants/brigitte_jellinek.json
> add participant Brigitte Jellinek

- participants/cristobal_heiss.json
> add Cristobal as participant

- participants/cowglow.json
- participants/marcoemrich.json
- src/pages/register.js
- test/participants.js
- test/tshirt-sizes.js
As mentioned in slack, we needed to add another t-shirt size:
https://jscraftcamp.slack.com/archives/CTV791PPY/p1653469228793329
@marcoemrich , @cowglow , I adapted the size in your registration as requested.
> add XXL as option, adapt page and test

- participants/lars_gregori.json
> add Lars Gregori to participants list

- participants/danielhilpoltsteiner.json
> Add Daniel Hilpoltsteiner to participants

- participants/dan.json
> register dan

- src/components/header/header.js
add link into header to the participants page
> add link to all participants

- participants/jakob.json
> Add participant jakob

- participants/gabrielbahniuk.json
> add gabrielbahniuk to participants

- participants/philip_lenhart.json
> add philip lenhart to participants

- participants/roberthostlowsky.json
- participants/sebastianfrefichs.json
> Add robert and sebastian

- participants/taghi_khavari.json
> request to register Taghi Khavari for JSCC 2022

- package.json
- src/pages/participants.js
- yarn.lock
Add a simple word cloud on participants page with all tags of the participants.
> add tags cloud on participants page

- participants/j_prince.json
> Registration: Jonathan Prince

- participants/amila_j.json
> Registration Amila

- participants/iaroslav_poliakov.json
> Registration: Iaroslav Poliakov

- participants/maksym_hopei.json
> Register to JSCraftCamp

- participants/maksym_hopei.json
I would like to update my registration data at JS CraftCamp.
I've just changed my twitter handle.
> Update twitter handle

- participants/simon_kindlein.json
> Added Simon to participants

- participants/cowglow.json
**Changes**
- I want to try something with the JS version of `p5`
- Better description to that story I share as my connection to JS
- Added `drum and bass` and `music`
Looking forward to hanging out again.
> Update `cowglow` Regristration

- participants/js.json
> add Jan to the list

- participants/oscar_fonseca.json
> Add Oscar Fonseca as participant

- participants/corinna_steinhoff.json
> Add Corinna as participant

- participants/peter-mbanugo.json
> Add Peter to Participants

- src/sections/schedule/schedule.js
Sono Motors sponsors the Saturday lunch, we should put this on the main website.
> Add sponsor for Saturday lunch

- .gitignore
- src/components/footer/footer.js
Footer was missing the Chromatic link:
* enable / add the Icon and Link to Storybook, built and used in Chromatic.
> Re enable chromatic storybook button

- CNAME
- gatsby-config.js
- package.json
- src/components/footer/footer.js
- src/data.json
- src/pages/index.js
- src/sections/intro/intro.js
Switch site to preparations for 2023
* switch year
* replace post-event with intro
* remove register link
* remove old sponsors section
> get ready for 2023

- src/routes/WhatYouCanExpect.svelte
- src/routes/sponsoring/Sponsors.svelte
... and fix some responsiveness issue with the "What to expect" part
> Fix Firefox not showing logos for sponsors

- src/lib/participants/Participant.svelte
- src/routes/participants/+page.svelte
I fixed a little layouting issue that could happen with longer names. While I was at the participants page, I created a clickable filter for the days.
Also resolves #1391
> Add filter for friday / saturday participants, fix layout issue

- participants/marco.json
> add Participant: Marco

- participants/ari.json
> "Add Ariadne Engelbrecht as participant."

- participants/matthias_stemmler.json
> Register Matthias Stemmler

- participants/vanessa_otto.json
> add participant Vanessa Otto

- participants/marc-dafeldecker.json
> add Marc to participants :)

- src/lib/participants/Participant.svelte
this is what the `title` attribute looks like (text is not exactly same as in screenshot)
> Add titles that show on hover what the icon means.

- src/lib/participants/participant-schema.ts
- static/schemas/participants.2023.json
There were some registrations with more text than 200 characters for connection or contribution. We want to allow longer texts.
> Increase limits for contribution and connection texts

- participants/christian_ranz.json
> Add Christian Ranz to participants.

- participants/dan.json
I will be there on both days :D
> edit participant "daniel weiß"

- package.json
- pnpm-lock.yaml
We should pin our dependencies, after having that written down in our README.md file 😅
Updated dependencies as well.
> chore: Update packages, pin dependencies

- participants/gabriel-birke.json
> Registration Gabriel Birke

- participants/fabian_biberger.json
> Registration Fabian Biberger

- participants/deniz_schmidt.json
Thanks, @meldron for [hinting out](https://github.com/jscraftcamp/website/pull/1455#issuecomment-1531330989)... would've been a nice surprise! 😄
> Fixing me being not smart enough to pick the right shirt type

- participants/piyush-biswal.json
> add piyush biswal

- participants/friedrich.json
> Adding Friedrich

- src/routes/sponsoring/Sponsors2023.svelte
Thanks to @woidda for pointing this out!
> Fix: Use correct link for sponsor

- participants/maksym_hopei.json
> Maksym Hopei - Register for JSCraftCamp

- participants/maksym_hopei.json
> Change tShirt.type to regular for maksym_hopei

- participants/lisi_linhart.json
> Registration Lisi Linhart

- participants/js.json
> Add Jan to the participants

- participants/tobias_sittenauer.json
- [] I asked my company about sponsoring (see open items at: https://github.com/orgs/jscraftcamp/projects/5/views/1)
> New Participant Tobias Sittenauer

- participants/theabdolah.json
> Update The Abdolah when.saturday to true

- participants/sebastian_hatzl.json
> feat: add new participant sebastian hatzl

- participants/christoph_hummel.json
> add christoph_hummel.josn

- participants/simon.json
> Register Simon

- participants/martin_grandrath.json
> Add participant Martin Grandrath

- participants/evgheni_poleacov.json
> Added participant Evgheni Poleacov

- participants/andys8.json
> add andys8

- src/routes/team/+page.svelte
Hey Team,
thank you all for organizing this years JSCC. As I am not part of the organizing crew, I'd love to be taken out of the team page - this already created some confusion as people reached out to me (I forwarded it to Wolfram / the official team mail).
Thans a lot!
> Removes David from the team (for now)

- src/routes/+page.svelte
- src/routes/Schedule.svelte
> feat: Add schedule

- participants/andreas_adam.json
update from upstreamI would like to register for JS CraftCamp.
> Andreas Adam wants to participate ☀️

- src/lib/participants/participant-schema.ts
- src/lib/participants/participants.spec.ts
- src/lib/participants/participants.ts
- src/routes/participants/+page.server.ts
- src/routes/participants/+page.svelte
- src/routes/participants/stats/+page.server.ts
- src/routes/participants/stats/+page.svelte
For the shirts and food orders, we need to see what we should order. With this page, we have some handy stats available.
> Add stats page

- participants/jakob.json
- x ] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
> Add Jakob as participant

- participants/markus_krogemann.json
- [ x] My pull request contains a JSON file `$name_or_nickname.json`
- [x ] The JSON file follows the template at [https://github.com/jscraftcamp/website/blob/main/participants/\_template.json](https://jscraftcamp.org/register/) and contains the mandatory fields like `name`, `when`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`
- [ x] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as participant. I acknowledge that my data are public on GitHub and I agree that I will be listed on the JSCraftCamp website as a …
> Add Markus Krogemann

- participants/tobi.json
> Add Tobi as participant

- participants/vbryan.json
> add participant

- participants/jose_riquelme.json
> Add Jose Riquelme Participant

- participants/yaroslav_poliakov.json
> registration: Yaroslav Poliakov

- participants/artiom_berdeu.json
> Added participant Artiom Berdeu

- participants/corinna_steinhoff.json
> Added participant Corinna Steinhoff

- .eslintrc.cjs
- .github/workflows/registration-tests.yml
- .prettierignore
- src/lib/layout/PhotoLayout.svelte
- src/lib/participants/Participant.svelte
- src/lib/participants/participant-schema.ts
- src/lib/participants/participants.spec.ts
- src/lib/participants/participants.ts
- src/routes/participants/+page.server.ts
- src/routes/participants/stats/+page.server.ts
This fixes some formatting/linting errors and also adds the lint step to the pipeline.
> Format and linting

- participants/jonathan_gottschalk.json
> Add Jonathan

- participants/michael_zoidl.json
As requested via Entwicklerstube Slack by @michaelzoidl, I'm removing Friday attendance for @michaelzoidl.
> Remove Friday attendance for @michaelzoidl as requested via Slack

- participants/luisa_venancio.json
> added luisa venancio

- src/routes/participants/stats/+page.server.ts
- src/routes/participants/stats/+page.svelte
Adding stats about how many different companies and people are registered
> Add stats for companies

- participants/florian_geierstanger.json
> Add florian

- participants/vanessa_otto.json
> update: Vanessa Otto, Saturday from false to true

- participants/yaroslav_poliakov.json
This PR is to move Yaroslav Poliakov (@altersign ) from the waiting list
> waiting list: add Friday for Yaroslav Poliakov

- participants/thomas-traenkler.json
> waiting list: add Friday for Thomas Tränkler

- participants/jonathan_gottschalk.json
> waiting list: Add Friday for jonathan

- participants/satya_roman.json
> Add Satya for Friday

- participants/stefan_hoferer.json
> add Stefan Hoferer

- participants/florian_geierstanger.json
This is a follow up PR to add myself on the Friday waiting list.
> waiting list: Add Friday for Florian

- participants/faisal_ahmed.json
> Add Faisal Ahmed as Participant

- src/lib/participants/registration.ts
> Registration closes 👋🏽

- src/lib/participants/registration.ts
- src/routes/+page.svelte
- src/routes/participants/+page.svelte
@wolframkriesing I should have tested the page before merging... 😅
> fix: Show participants when registration is closed

- src/lib/layout/PhotoLayout.svelte
- src/routes/participants/stats/+page.server.ts
There are some warnings on every PR right now. This PR should fix them.
> Fix warnings visible on PRs

- participants/maheshwaran_velusamy.json
> Maheshwaran velusamy

- src/routes/sponsoring/Partners.svelte
Seneca dates for 2024 are here so I went ahead and updated it in your partner section :)
> Update Seneca dates for 2024

- src/routes/+page.svelte
> Add date and location

- src/routes/+page.svelte
Adds the address of the location to the frontpage
> Add the address to the frontpage and adjust date format

- participants/wolfram.json
> Registration: Wolfram Kriesing

- participants/korbinianfritsch.json
> Add korbinianfritsch to participants

- participants/maheshwaran_velusamy.json
> Registration maheshwaran velusamy

- participants/christian_ranz.json
> Add Christian Ranz to participants

- participants/maheshwaran_velusamy.json
> maheshwaran velusamy : Updated the Tags and contribution

- participants/henryk.json
> Create Registration Request

- participants/vanessa_otto.json
> Add Vanessa Otto

- participants/florian_rappl.json
> Add Florian Rappl

- participants/jonathan_prince.json
> add registration for jonathan

- participants/malie_bertram.json
> Create participant malie_bertram.json

- participants/joluj.json
> Register Johannes Jablonski

- participants/fchristl.json
> add fchristl

- participants/yaroslav_poliakov.json
> Registration for Yaroslav Poliakov

- participants/tamara.json
> Registration Tamara

- participants/christian_stief.json
> Add Christian Stief to participants

- participants/vladimir_bryantsev.json
> Added participant Vladimir Bryantsev

- participants/georgiee.json
> docs(participants): add georgiee

- participants/djg.json
> Add registration for Dirk Gomez

- src/lib/sponsoring/Partners.svelte
With this PR, I propose to update the SoCraTes conference dates to the 2024 edition dates
> Update Partners.svelte with SoCraTes 2024 dates

- participants/lukastaegert.json
> Registration Lukas Taegert-Atkinson

- participants/albertodiazdorado.json
> Sign up Alberto Diaz Dorado

- participants/ariadne.json
> Add participant Ariadne Engelbrecht

- participants/luca_asmus.json
> Add luca_asmus.json

- participants/krishnasingh.json
> Add participant Krishna Singh

- participants/robert-hostlowsky.json
> add robert

- src/routes/Schedule.svelte
Now sure who will be the facilitator this year - removing previous one from page.
> prep-who-will-be-the-facilitator

- participants/stefan_spittank.json
> Added stefan_spittank.json

- participants/trishul.json
> registration for Trishul

- participants/herrherrmann.json
> Add Sebastian Herrmann

- src/routes/registration/+page.svelte
> Add disclaimer for dietary requirements

- src/routes/+page.svelte
> Add pricing information - it is free

- participants/andreas_houben.json
> added andreas_houben.json

- participants/birgit_fuchs.json
> docs(participants): add birgit_fuchs

- participants/love.json
> adding love okum as participant

- participants/dejanr.json
> Add Dejan Ranisavljevic as participant

- src/lib/participants/participant-schema.ts
See https://github.com/jscraftcamp/website/pull/2024 :)
> Make tShirtSize actually optional

- participants/conny.json
> Adds Conny as a participant

- participants/larisa_dolgova.json
> Add Larisa as a participant

- participants/corinna_steinhoff.json
> Add Corinna Steinhoff as participant

- participants/lakha.json
> Participation in JSCraftCamp

- participants/christian_waldmann.json
> Add Christian W as a participant

- participants/jesusreal.json
I am already registered for JS CraftCamp. This PR updates my participation.
> chore: update participation

- participants/michael_zoidl.json
> Register Michael Zoidl and fix Patrick Müller company

- participants/mahyar.json
> add Mahyar Shabani to participants

- participants/celestine_auburger.json
- participants/hannes_randow.json
> Add Hannes as a participant

- participants/kai-kopecky.json
- participants/philip-saa.json
Updating company on two participants
> Update participant registration

- participants/oleksandr_markovskyi.json
- participants/vitaliia_markovska.json
- [ y ] My pull request contains a JSON file `$name_or_nickname.json`
- [ y ] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
- [ y ] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ y ] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count …
> Updated 'when'

- participants/fiis_husband.json
- [X ] My pull request contains a JSON file `$name_or_nickname.json`
- [X ] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
- [X ] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ X] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me …
> add Fii's husband

- README.md
I've pushed the change to add a sponsor on main by accident and now set up branch protection rules for main to not let a commit be pushed to main directly by anybody. Let's see that this works by doing it via a PR.
> Ensure branch protection rules work

- participants/narigo.json
> Add Jörn as participant

- participants/matthias-stemmler.json
> Add Matthias as participant

- participants/dtmzr.json
> Add Deniz Schmidt as participant

- participants/bruno.json
> Add Bruno as a participant

- participants/philiplenhart.json
> add Philip as participant

- participants/paris.json
> Add a new participant (Sergej)

- participants/marc.json
> add marc as participant

- participants/daniel.json
> Add Daniel as a participant

- participants/kai.json
> Add Kai as participant

- participants/leeburton.json
> Add Lee Burton as participant

- .github/PULL_REQUEST_TEMPLATE.md
Just a small addition to the PR template to see more registrations like #2119 and #2111 😅
> Add an optional GIF to show some excitement in registration

- participants/akash.json
> Add akash as a participant

- participants/oliver.json
- [x ] My pull request contains a JSON file `oliver.json`
- [x ] I read the `THE IMPORTANT STUFF` at [https://jscraftcamp.org/registration](https://jscraftcamp.org/registration), the JSON file follows the [template](https://github.com/jscraftcamp/website/blob/main/participants/_template.json), and contains the mandatory fields like `realName`, `githubAccountName`, `when`, `iCanTakeNotesDuringSessions`, `whatIsMyConnectionToJavascript` and `whatCanIContribute`.
- [x ] If I can NOT attend, I will either send another pull request removing my JSON file or an e-mail with the subject 'UNREGISTER' to team@jscraftcamp.org
- [ x] I agree that the data I enter in the registration can be used for running the event, e.g. make a name tag, count me as …
> Add Oliver Tigges as participant.

- src/lib/participants/Participant.svelte
Looks like the dates from last year are still showing
> fix: correct 2025 dates in participant comp

- participants/mixn.json
> Add mixn as a participant

- participants/stefan.json
> feat: add stefan

- participants/domachine.json
> add domachine participant

- participants/mariovolke.json
> Add mariovolke to participants

- participants/jonathan.json
> feat: add jonathan

- participants/charlyoleg.json
> add participant charlyoleg.json

- participants/abdolah-keshtkar.json
> Add Abdolah Keshtkar

- participants/hamideh.json
> Add hamideh to participants

- participants/lukastaegert.json
> Add Lukas Taegert-Atkinson

- participants/michael-zoidl.json
[**Optional GIF to show my level of excitement**
> its a me michael

- participants/abbas.json
> Update abbas.json with correct company name

- participants/florian.json
> Add participant florian

- participants/deni.json
I just changed my username, so I'd like to fix the JSON
> Update Deni username

- participants/christianstricker.json
> feat: Adding Christian as participant

- participants/martin_grandrath.json
> add martin_grandrath.json

- participants/tobias_oettl.json
> added tobias oettl

- participants/shah_saquib.json
@Narigo, this is the new PR for updating my company name.
> Please add shah_saquib.json and remove shah.json

- participants/chiawei_ong.json
> feat: add chiawei_ong.json

- src/lib/sponsoring/Sponsors2025.svelte
> Hetzner sponsors 500,- (not 300,-)

- participants/js.json
> register Jan with js.json

- participants/andrei_shingirii.json
> Add participant Andrei Shingirii

- participants/mansi.json
> Registration for Michael Mannseicher 

- participants/robert-hostlowsky.json
THANKS, Team, for organising the JSCraftcamp 2025. You are:
> register robert

- participants/tobiassittenauer.json
> feat: add participant tobias sittenauer

- participants/charlyoleg.json
I'm already registered. Just want to update my website url.
> update website url of charlyoleg

- participants/dtmzr.json
Sadly won't be able to make it on Friday but looking forward for Saturday!
> Update dtmzr participation

- participants/robert-hostlowsky.json
> update: Robert wants to attends on Friday

- participants/max_hopei.json
> Create max_hopei Friday & Sat

- participants/steff.json
**We would like to register for JS CraftCamp on Friday if there is any possibility for it**
> Waitlist Participants (Tobias & Stefan) for Friday

- participants/max_hopei.json
Destiny is a strange thing. Unfortunately, I have to finally cancel Friday, as something urgent just popped up. Very sorry about that!
> Decline Friday
